/**
 * ActBlue integration type definitions
 */

export type ActBlueEventType = 'donation' | 'refund' | 'cancellation';
export type ActBlueCsvType = 'paid_contributions' | 'refunded_contributions' | 'cancelled_recurring_contributions' | 'managed_form_contributions';
export type ActBlueImportStatus = 'pending' | 'processing' | 'completed' | 'failed';

// ActBlue Config
export interface ActBlueConfig {
  id: string;
  workspaceId: string;
  apiKey?: string;
  webhookUsername: string;
  webhookPasswordHash?: string; // Never returned to client
  isWebhookEnabled: boolean;
  isCsvImportEnabled: boolean;
  metadata?: Record<string, any>;
  createdAt: string;
  updatedAt: string;
}

export interface CreateActBlueConfigData {
  apiKey?: string;
  webhookUsername: string;
  webhookPassword: string; // Will be hashed before storing
  isWebhookEnabled?: boolean;
  isCsvImportEnabled?: boolean;
  metadata?: Record<string, any>;
}

export interface UpdateActBlueConfigData {
  apiKey?: string;
  webhookUsername?: string;
  webhookPassword?: string; // Will be hashed before storing
  isWebhookEnabled?: boolean;
  isCsvImportEnabled?: boolean;
  metadata?: Record<string, any>;
}

// ActBlue Webhook Log
export interface ActBlueWebhookLog {
  id: string;
  workspaceId: string;
  eventType: ActBlueEventType;
  actblueOrderNumber?: string;
  payload: Record<string, any>;
  processedAt?: string;
  status: 'success' | 'failed' | 'pending';
  errorMessage?: string;
  createdAt: string;
}

// ActBlue Import
export interface ActBlueImport {
  id: string;
  workspaceId: string;
  importType: 'webhook' | 'csv';
  filename?: string;
  csvType?: ActBlueCsvType;
  dateRangeStart?: string;
  dateRangeEnd?: string;
  totalRecords: number;
  processedRecords: number;
  successfulRecords: number;
  failedRecords: number;
  status: ActBlueImportStatus;
  errorLog?: Record<string, any>;
  createdAt: string;
  completedAt?: string;
  createdById?: string;
}

export interface CreateActBlueImportData {
  workspaceId: string;
  importType: 'webhook' | 'csv';
  filename?: string;
  csvType?: ActBlueCsvType;
  dateRangeStart?: string;
  dateRangeEnd?: string;
  totalRecords: number;
}

// ActBlue Webhook Payloads (based on ActBlue API documentation)

export interface ActBlueDonor {
  firstname: string;
  lastname: string;
  addr1: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  isEligibleForExpressLane: boolean;
  employerData?: {
    employer?: string;
    occupation?: string;
    employerAddr1?: string;
    employerCity?: string;
    employerState?: string;
    employerCountry?: string;
  };
  email?: string;
  phone?: string;
}

export interface ActBlueLineItem {
  sequence: number;
  entityId: number;
  fecId?: string;
  committeeName: string;
  amount: string;
  recurringAmount?: string;
  paidAt: string;
  paymentId?: string;
  lineitemId: number;
  amountLessAbFees?: string;
}

export interface ActBlueContribution {
  createdAt: string;
  orderNumber: string;
  contributionForm: string;
  refcode?: string;
  refcode2?: string;
  refcodes?: Record<string, string>;
  creditCardExpiration?: string;
  recurringPeriod: 'once' | 'weekly' | 'monthly';
  recurringDuration?: number | string;
  weeklyRecurringSunset?: string;
  abTestName?: string;
  isRecurring?: string;
  isPaypal: boolean;
  isMobile: boolean;
  abTestVariation?: string;
  isExpress: boolean;
  withExpressLane: boolean;
  expressSignup: boolean;
  uniqueIdentifier?: string;
  status: 'approved' | 'declined' | 'pending';
  thanksUrl?: string;
  retryUrl?: string;
  textMessageOption?: 'unknown' | 'opt_in' | 'opt_out';
  giftDeclined?: boolean;
  giftIdentifier?: number;
  shippingName?: string;
  shippingAddr1?: string;
  shippingCity?: string;
  shippingState?: string;
  shippingZip?: string;
  shippingCountry?: string;
  smartBoostAmount?: string;
  customFields?: Array<{
    label: string;
    answer: string;
  }>;
  merchandise?: Array<{
    name: string;
    itemId: number;
    details?: Record<string, any>;
  }>;
  bumpYourRecurring?: {
    bumpRecurringLink?: string;
    recurringUpsellSeen?: boolean;
    recurringUpsellAccepted?: boolean;
  };
}

export interface ActBlueForm {
  name: string;
  kind: 'page' | 'merchandise' | 'event' | 'embed' | 'autogenerated';
  managingEntityName?: string;
  managingEntityCommitteeName?: string;
  ownerEmail?: string;
}

export interface ActBlueDonationWebhook {
  donor: ActBlueDonor;
  contribution: ActBlueContribution;
  lineitems: ActBlueLineItem[];
  form: ActBlueForm;
}

export interface ActBlueRefundLineItem {
  refundedAt: string;
  disbursedAt?: string;
  recoveredAt?: string;
}

export interface ActBlueRefundWebhook {
  donor: ActBlueDonor;
  contribution: ActBlueContribution;
  lineitems: (ActBlueLineItem & ActBlueRefundLineItem)[];
  form: ActBlueForm;
}

export interface ActBlueCancellationContribution extends Omit<ActBlueContribution, 'status'> {
  cancelledAt: string;
  recurringType: 'initially forever' | 'initially monthly' | 'initially weekly' | 'initially monthly adjustable';
  recurCompleted: number;
  recurPledged: number;
  cancellationReason?: string;
  cancellationType: 'Active' | 'Lapsed' | 'Other';
}

export interface ActBlueCancellationWebhook {
  donor: ActBlueDonor;
  contribution: ActBlueCancellationContribution;
  lineitems: ActBlueLineItem[];
  form: ActBlueForm;
}

// CSV API Types
export interface RequestCsvData {
  csvType: ActBlueCsvType;
  dateRangeStart: string; // YYYY-MM-DD
  dateRangeEnd: string; // YYYY-MM-DD
}

export interface CsvRequestResponse {
  id: string;
}

export interface CsvStatusResponse {
  id: string;
  downloadUrl?: string;
  status: 'in_progress' | 'complete';
}

// Contact Matching Types
export interface ContactMatchCandidate {
  contactId: string;
  confidence: number;
  matchType: 'email' | 'name_address' | 'name_zip' | 'name_phone';
  matchedFields: string[];
}

export interface ContactMatchResult {
  matched: boolean;
  contactId?: string;
  confidence: number;
  candidates: ContactMatchCandidate[];
  shouldCreateNew: boolean;
}
